set time on
set timing on
ALTER SESSION SET ddl_lock_timeout=600;
DROP TABLE FCC114.GLTEMP PURGE;
DROP TABLE FCC114.ICTB_ENTRIES_HIST_ARC2018 PURGE;
DROP TABLE FCC114.TEMP_TBL_5151 PURGE;
DROP TABLE FCC114.API_DEBUG_DATA PURGE;
DROP TABLE FCC114.ICTB_ENTRIES_HISTORY_ARCHIVE PURGE;

