  CREATE INDEX "FCC114"."STTM_CUSTOMER_CUSTPAR" ON "FCC114"."STTM_CUSTOMER" ("CUSTOMER_NO","SHORT_NAME","CUSTOMER_NAME1") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) LOCAL
 (PARTITION "STTM_CUST_HASH_P100" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P101" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P102" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P103" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P104" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P105" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P106" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P107" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P108" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P109" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P110" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P111" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P112" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P113" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P114" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P115" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P116" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P117" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P118" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P119" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P120" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P121" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P122" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P123" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P124" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P125" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P126" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P127" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P128" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P129" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P130" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P131" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P132" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P133" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P134" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P135" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P136" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P137" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P138" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P139" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P140" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P141" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P142" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P143" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P144" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P145" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P146" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P147" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P148" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P149" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P150" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P151" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P152" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P153" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P154" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P155" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P156" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P157" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P158" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P159" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P160" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P161" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P162" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P163" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P164" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P165" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P166" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P167" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P168" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P169" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P170" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P171" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P172" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P173" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P174" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P175" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P176" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P177" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P178" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P179" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P180" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P181" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P182" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P183" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P184" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P185" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P186" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P187" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P188" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P189" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P190" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P191" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P192" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P193" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P194" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P195" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P196" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P197" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P198" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P199" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P200" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P201" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P202" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P203" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P204" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P205" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P206" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P207" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P208" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P209" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P210" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P211" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P212" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P213" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P214" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P215" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P216" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P217" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P218" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P219" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P220" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P901" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P902" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P998" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P999" 
  TABLESPACE "FCCDATALAR" ) 
  PARALLEL 16;

alter index FCC114.STTM_CUSTOMER_CUSTPAR noparallel;