
  CREATE TABLE "FCC114"."STTM_CUSTOMER" 
   (	"CUSTOMER_NO" VARCHAR2(9 BYTE), 
	"CUSTOMER_TYPE" CHAR(1 BYTE), 
	"CUSTOMER_NAME1" VARCHAR2(105 BYTE), 
	"ADDRESS_LINE1" VARCHAR2(105 BYTE), 
	"ADDRESS_LINE3" VARCHAR2(105 BYTE), 
	"ADDRESS_LINE2" VARCHAR2(105 BYTE), 
	"ADDRESS_LINE4" VARCHAR2(105 BYTE), 
	"COUNTRY" VARCHAR2(3 BYTE), 
	"SHORT_NAME" VARCHAR2(20 BYTE), 
	"NATIONALITY" VARCHAR2(3 BYTE), 
	"LANGUAGE" VARCHAR2(3 BYTE), 
	"EXPOSURE_COUNTRY" VARCHAR2(3 BYTE), 
	"LOCAL_BRANCH" VARCHAR2(3 BYTE), 
	"LIABILITY_NO" VARCHAR2(9 BYTE), 
	"UNIQUE_ID_NAME" VARCHAR2(20 BYTE), 
	"UNIQUE_ID_VALUE" VARCHAR2(20 BYTE), 
	"FROZEN" CHAR(1 BYTE), 
	"DECEASED" CHAR(1 BYTE), 
	"WHEREABOUTS_UNKNOWN" CHAR(1 BYTE), 
	"CUSTOMER_CATEGORY" VARCHAR2(10 BYTE), 
	"HO_AC_NO" VARCHAR2(105 BYTE), 
	"RECORD_STAT" CHAR(1 BYTE), 
	"AUTH_STAT" CHAR(1 BYTE), 
	"MOD_NO" NUMBER(4,0), 
	"MAKER_ID" VARCHAR2(12 BYTE), 
	"MAKER_DT_STAMP" DATE, 
	"CHECKER_ID" VARCHAR2(12 BYTE), 
	"CHECKER_DT_STAMP" DATE, 
	"ONCE_AUTH" CHAR(1 BYTE) DEFAULT 'N', 
	"FX_CUST_CLEAN_RISK_LIMIT" NUMBER(22,3), 
	"OVERALL_LIMIT" NUMBER(24,3), 
	"FX_CLEAN_RISK_LIMIT" NUMBER(24,3), 
	"CREDIT_RATING" VARCHAR2(10 BYTE), 
	"REVISION_DATE" DATE, 
	"LIMIT_CCY" VARCHAR2(3 BYTE), 
	"CAS_CUST" CHAR(1 BYTE), 
	"LIAB_NODE" VARCHAR2(105 BYTE), 
	"SEC_CUST_CLEAN_RISK_LIMIT" NUMBER(22,3), 
	"SEC_CLEAN_RISK_LIMIT" NUMBER(22,3), 
	"SEC_CUST_PSTL_RISK_LIMIT" NUMBER(22,3), 
	"SEC_PSTL_RISK_LIMIT" NUMBER(22,3), 
	"LIAB_BR" VARCHAR2(3 BYTE), 
	"PAST_DUE_FLAG" VARCHAR2(1 BYTE), 
	"DEFAULT_MEDIA" VARCHAR2(15 BYTE), 
	"SSN" VARCHAR2(11 BYTE), 
	"SWIFT_CODE" VARCHAR2(12 BYTE), 
	"LOC_CODE" VARCHAR2(3 BYTE), 
	"SHORT_NAME2" VARCHAR2(20 BYTE), 
	"UTILITY_PROVIDER" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"UTILITY_PROVIDER_ID" VARCHAR2(35 BYTE), 
	"RISK_PROFILE" VARCHAR2(20 BYTE), 
	"DEBTOR_CATEGORY" VARCHAR2(10 BYTE), 
	"FULL_NAME" VARCHAR2(105 BYTE), 
	"UDF_1" VARCHAR2(150 BYTE), 
	"UDF_2" VARCHAR2(150 BYTE), 
	"UDF_3" VARCHAR2(150 BYTE), 
	"UDF_4" VARCHAR2(150 BYTE), 
	"UDF_5" VARCHAR2(150 BYTE), 
	"AML_REQUIRED" CHAR(1 BYTE), 
	"AML_CUSTOMER_GRP" VARCHAR2(9 BYTE), 
	"MAILERS_REQUIRED" CHAR(1 BYTE), 
	"GROUP_CODE" VARCHAR2(10 BYTE), 
	"EXPOSURE_CATEGORY" VARCHAR2(20 BYTE), 
	"CUST_CLASSIFICATION" VARCHAR2(20 BYTE), 
	"CIF_STATUS" VARCHAR2(20 BYTE), 
	"CIF_STATUS_SINCE" DATE, 
	"CHARGE_GROUP" VARCHAR2(10 BYTE), 
	"INTRODUCER" VARCHAR2(9 BYTE), 
	"CUST_CLG_GROUP" VARCHAR2(10 BYTE), 
	"CHK_DIGIT_VALID_REQD" VARCHAR2(1 BYTE), 
	"ALG_ID" VARCHAR2(20 BYTE), 
	"FT_ACCTING_AS_OF" VARCHAR2(1 BYTE), 
	"UNADVISED" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"TAX_GROUP" VARCHAR2(10 BYTE), 
	"CONSOL_TAX_CERT_REQD" VARCHAR2(1 BYTE), 
	"INDIVIDUAL_TAX_CERT_REQD" VARCHAR2(1 BYTE), 
	"CLS_CCY_ALLOWED" VARCHAR2(1 BYTE) DEFAULT 'D', 
	"CLS_PARTICIPANT" VARCHAR2(1 BYTE), 
	"FX_NETTING_CUSTOMER" VARCHAR2(9 BYTE), 
	"RISK_CATEGORY" VARCHAR2(4 BYTE), 
	"FAX_NUMBER" VARCHAR2(105 BYTE), 
	"EXT_REF_NO" VARCHAR2(20 BYTE), 
	"CRM_CUSTOMER" VARCHAR2(1 BYTE), 
	"ISSUER_CUSTOMER" VARCHAR2(1 BYTE), 
	"TREASURY_CUSTOMER" VARCHAR2(1 BYTE), 
	"CIF_CREATION_DATE" DATE, 
	"WHT_PCT" NUMBER, 
	"RP_CUSTOMER" VARCHAR2(1 BYTE), 
	"GENERATE_MT920" VARCHAR2(1 BYTE), 
	"KYC_DETAILS" VARCHAR2(1 BYTE), 
	"STAFF" VARCHAR2(1 BYTE), 
	"KYC_REF_NO" VARCHAR2(16 BYTE), 
	"UTILITY_PROVIDER_TYPE" VARCHAR2(35 BYTE), 
	"JOINT_VENTURE" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"JV_LIMIT_TRACKING" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"PRIVATE_CUSTOMER" VARCHAR2(1 BYTE), 
	"LC_COLLATERAL_PCT" NUMBER(7,4), 
	"ELCM_CUSTOMER" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"ELCM_CUSTOMER_NO" VARCHAR2(20 BYTE), 
	"AUTO_CREATE_ACCOUNT" CHAR(1 BYTE) DEFAULT 'N', 
	"AUTO_CUST_AC_NO" VARCHAR2(20 BYTE), 
	"TRACK_LIMITS" CHAR(1 BYTE) DEFAULT 'N', 
	"AR_AP_TRACKING" VARCHAR2(1 BYTE), 
	"DATE_OF_BIRTH" DATE, 
	 CONSTRAINT "PK01_STTM_CUSTOMER" PRIMARY KEY ("CUSTOMER_NO")
  USING INDEX PCTFREE 10 INITRANS 8 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCC114"  ENABLE, 
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) PCTFREE 10 PCTUSED 40 INITRANS 8 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCCDATALAR" 
  PARTITION BY HASH ("CUSTOMER_NO") 
 (PARTITION "STTM_CUST_HASH_P100" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P101" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P102" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P103" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P104" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P105" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P106" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P107" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P108" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P109" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P110" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P111" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P112" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P113" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P114" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P115" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P116" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P117" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P118" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P119" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P120" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P121" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P122" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P123" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P124" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P125" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P126" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P127" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P128" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P129" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P130" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P131" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P132" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P133" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P134" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P135" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P136" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P137" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P138" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P139" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P140" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P141" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P142" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P143" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P144" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P145" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P146" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P147" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P148" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P149" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P150" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P151" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P152" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P153" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P154" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P155" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P156" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P157" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P158" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P159" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P160" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P161" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P162" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P163" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P164" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P165" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P166" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P167" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P168" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P169" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P170" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P171" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P172" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P173" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P174" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P175" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P176" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P177" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P178" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P179" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P180" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P181" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P182" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P183" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P184" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P185" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P186" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P187" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P188" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P189" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P190" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P191" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P192" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P193" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P194" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P195" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P196" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P197" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P198" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P199" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P200" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P201" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P202" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P203" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P204" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P205" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P206" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P207" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P208" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P209" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P210" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P211" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P212" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P213" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P214" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P215" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P216" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P217" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P218" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P219" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P220" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P901" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P902" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P998" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS , 
 PARTITION "STTM_CUST_HASH_P999" SEGMENT CREATION IMMEDIATE 
  TABLESPACE "FCCDATALAR" 
 NOCOMPRESS )  ENABLE ROW MOVEMENT ;

  CREATE INDEX "FCC114"."IDX_STTM_CUST2" ON "FCC114"."STTM_CUSTOMER" ("UNIQUE_ID_NAME"||"UNIQUE_ID_VALUE") 
  PCTFREE 10 INITRANS 8 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCCINDXMED" 
  PARALLEL 4 ;

  CREATE INDEX "FCC114"."INDX1_STTM_CUSTOMER" ON "FCC114"."STTM_CUSTOMER" ("LIABILITY_NO") 
  PCTFREE 10 INITRANS 8 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCCINDXMED" 
  PARALLEL 4 ;

  CREATE INDEX "FCC114"."IX05_STTMS_CUSTOMER" ON "FCC114"."STTM_CUSTOMER" ("CUSTOMER_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCCINDXMED" 
  PARALLEL 4 ;

  CREATE INDEX "FCC114"."STTM_CUSTOMER_CONV1" ON "FCC114"."STTM_CUSTOMER" ("SHORT_NAME") 
  PCTFREE 10 INITRANS 8 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCCINDXMED" 
  PARALLEL 4 ;

  CREATE INDEX "FCC114"."STTM_CUSTOMER_CONV2" ON "FCC114"."STTM_CUSTOMER" ("EXT_REF_NO") 
  PCTFREE 10 INITRANS 8 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCCINDXMED" 
  PARALLEL 4 ;

  CREATE INDEX "FCC114"."STTM_CUSTOMER_CONV3" ON "FCC114"."STTM_CUSTOMER" ("UNIQUE_ID_NAME", "UNIQUE_ID_VALUE") 
  PCTFREE 10 INITRANS 8 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCCINDXMED" 
  PARALLEL 4 ;

  CREATE UNIQUE INDEX "FCC114"."STTM_CUSTOMER_CUSBRN" ON "FCC114"."STTM_CUSTOMER" ("LOCAL_BRANCH", "CUSTOMER_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCC114" ;

  CREATE INDEX "FCC114"."STTM_CUST_REC_INX" ON "FCC114"."STTM_CUSTOMER" ("RECORD_STAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCCINDXMED" 
  PARALLEL 4 ;

  CREATE UNIQUE INDEX "FCC114"."STTM_CUSTOMER_CUSTNO" ON "FCC114"."STTM_CUSTOMER" ("CUSTOMER_NO", "ACCOUNT_CLASS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCC114" ;


  CREATE INDEX "FCC114"."STTM_CUST_REC_INX1" ON "FCC114"."STTM_CUSTOMER" ("RECORD_STAT", "ONCE_AUTH") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) LOCAL
 (PARTITION "STTM_CUST_HASH_P100" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P101" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P102" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P103" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P104" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P105" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P106" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P107" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P108" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P109" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P110" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P111" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P112" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P113" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P114" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P115" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P116" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P117" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P118" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P119" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P120" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P121" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P122" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P123" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P124" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P125" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P126" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P127" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P128" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P129" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P130" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P131" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P132" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P133" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P134" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P135" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P136" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P137" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P138" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P139" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P140" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P141" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P142" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P143" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P144" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P145" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P146" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P147" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P148" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P149" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P150" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P151" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P152" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P153" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P154" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P155" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P156" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P157" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P158" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P159" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P160" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P161" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P162" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P163" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P164" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P165" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P166" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P167" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P168" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P169" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P170" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P171" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P172" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P173" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P174" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P175" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P176" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P177" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P178" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P179" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P180" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P181" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P182" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P183" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P184" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P185" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P186" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P187" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P188" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P189" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P190" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P191" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P192" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P193" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P194" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P195" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P196" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P197" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P198" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P199" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P200" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P201" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P202" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P203" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P204" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P205" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P206" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P207" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P208" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P209" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P210" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P211" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P212" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P213" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P214" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P215" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P216" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P217" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P218" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P219" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P220" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P901" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P902" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P998" 
  TABLESPACE "FCCDATALAR" , 
 PARTITION "STTM_CUST_HASH_P999" 
  TABLESPACE "FCCDATALAR" ) ;

  CREATE UNIQUE INDEX "FCC114"."UI01_STTM_CUSTOMER" ON "FCC114"."STTM_CUSTOMER" ("UTILITY_PROVIDER_ID") 
  PCTFREE 10 INITRANS 8 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCCINDXLAR" 
  PARALLEL 4 ;

  CREATE UNIQUE INDEX "FCC114"."UI02_STTM_CUSTOMER" ON "FCC114"."STTM_CUSTOMER" ("SSN") 
  PCTFREE 10 INITRANS 8 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCCINDXLAR" 
  PARALLEL 4 ;

  CREATE INDEX "FCC114"."X3_STTM_CUSTOMER" ON "FCC114"."STTM_CUSTOMER" ("SWIFT_CODE") 
  PCTFREE 10 INITRANS 8 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCCINDXMED" 
  PARALLEL 4 ;

  CREATE INDEX "FCC114"."XX22_STTMS_CUSTOMER" ON "FCC114"."STTM_CUSTOMER" ("CUSTOMER_CATEGORY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FCC114" 
  PARALLEL 4 ;

  CREATE OR REPLACE TRIGGER "FCC114"."GWTR#_TRG_CUST" AFTER UPDATE OR INSERT ON "FCC114"."STTM_CUSTOMER" FOR EACH ROW  WHEN (new.auth_stat='A') DECLARE
    l_Operation VARCHAR2(20);
    l_Pk_Cols   VARCHAR2(32767);
    l_Pk_Vals   VARCHAR2(32767);
    l_Rowid     VARCHAR2(32767);
    l_Notify    VARCHAR2(10) := 'Y';
BEGIN
l_Notify:= 'Y';
IF inserting THEN
l_Operation := 'INSERT';
ELSE
l_Operation := 'UPDATE';
END IF;
IF NVL(:old.once_auth, 'N') <> 'Y' THEN
    l_Operation := 'INSERT';
ELSE
    l_Operation := 'UPDATE';
END IF;
IF NVL(l_Notify,'N') = 'Y' THEN
l_Pk_Cols := 'CUSTOMER_NO';
l_Pk_Vals := :New.CUSTOMER_NO;
l_RowId    := :New.Rowid;
Pr_Populate_Notification('STTM_CUSTOMER',
l_Pk_Cols,
l_Pk_Vals,
l_Operation,
l_RowId,
'');
 END IF;
EXCEPTION
WHEN OTHERS THEN
Debug.Pr_Debug('ST','Failed in gwtr#_CSTM_PRODUCT. Error = ' || SQLERRM);
END GWTR#_TRG_CUST;





/
ALTER TRIGGER "FCC114"."GWTR#_TRG_CUST" DISABLE;

  CREATE OR REPLACE TRIGGER "FCC114"."STTR_CUST_AC_JOINT" AFTER UPDATE OF "CUSTOMER_NAME1" ON "FCC114"."STTM_CUSTOMER" FOR EACH ROW 
BEGIN
	debug.pr_debug('AC','In trigger sttr_cust_ac_joint ');
	UPDATE sttms_ac_linked_entities
	SET joint_holder_description = :NEW.customer_name1
	WHERE joint_holder_code = :new.customer_no;
	debug.pr_debug('AC','End of trigger sttr_cust_ac_joint ');
EXCEPTION
WHEN OTHERS
THEN
	debug.pr_debug('AC','In exception in trigger sttr_cust_ac_joint  '||sqlerrm);
END sttr_cust_ac_joint;

/
ALTER TRIGGER "FCC114"."STTR_CUST_AC_JOINT" ENABLE;

  CREATE OR REPLACE TRIGGER "FCC114"."STTMS_CUSTOMER_DELETE" AFTER DELETE ON "FCC114"."STTM_CUSTOMER" FOR EACH ROW 
BEGIN
	DELETE from svtms_cif_sig_master
	WHERE cif_id = :old.customer_no;
	DELETE svtms_cif_sig_det
	WHERE cif_id = :old.customer_no;
	DELETE svtms_cif_sig_branches
	WHERE cif_id = :old.customer_no;
END;

/
ALTER TRIGGER "FCC114"."STTMS_CUSTOMER_DELETE" ENABLE;

  CREATE OR REPLACE TRIGGER "FCC114"."ELTR_STTM_CUSTOMER" BEFORE UPDATE OR INSERT OF "RECORD_STAT", "AUTH_STAT" ON "FCC114"."STTM_CUSTOMER" FOR EACH ROW DECLARE

	l_error_code  varchar2(255);
	l_error_prms  varchar2(255);
	-- Log#1 Changes Start
	l_function_id		VARCHAR2(8);
	l_branch_code		VARCHAR2(3);
	l_key          	VARCHAR2(3000);
	l_data         	VARCHAR2(3000);
	l_mod_no       	NUMBER := 1;
	l_priority			NUMBER := 9;
	err_return 			EXCEPTION;
	l_count       	NUMBER := 0;
	-- Log#1 Changes End
--	 pragma autonomous_transaction;			-- Kernel 11.3 Changes - elpks_cache.fn_delte_cache is having autonomus txn, hence removing fm here


BEGIN
    IF nvl(:new.track_limits, 'N') = 'Y'
    THEN
        -- will be handled part of auto liab creation as web service call
        RETURN;
    END IF;

	--dbms_output.put_line('Inside Trigger eltr_sttm_customer...');
	debug.pr_debug('LM', 'call elcm componet ---->' );

	IF :NEW.auth_stat = 'A'
	THEN

	IF  Cspks_Os_Param.Get_Param_Val('ELCM_SETUP_MODE') not in ('S', 'H')

	THEN
		debug.pr_debug('LM', 'call elcm componet ---->' );
		IF NOT elpks_cache.fn_delete_cache ( 	'R'
								,	 'STTM_CUSTOMER'
								--,	 'BRANCH_CODE#CCY1#CCY2'
								,	  :NEW.customer_no || '#'
								,	 l_error_code
								,	l_error_prms
								)
			THEN

				debug.pr_debug('LM', 'failed in elcm componet ---->' );

			END IF;

			IF :NEW.elcm_customer = 'Y' THEN

				:NEW.elcm_customer_no := :NEW.customer_no;
			END IF;

	else

		-- Kernel 11.3 Chagnes - Start
		debug.pr_debug('LM', 'Calling Replication program...' );

		IF :NEW.elcm_customer = 'Y'
		AND :NEW.ELCM_CUSTOMER_NO IS NULL
		THEN
			SELECT COUNT(1)
			INTO l_count
			FROM getm_parameter
			WHERE gen_customer_no ='N';

				IF l_count > 0 THEN

					:NEW.ELCM_CUSTOMER_NO := :NEW.customer_no;
				END IF;
		END IF;

		l_function_id := 'CODCIFDF';
		l_branch_code := global.current_branch;
		l_key := :new.customer_no;							-- PK for STTM_CUSTOMER - CUSTOMER_NO


		elpkss_replication.g_stdcif_elcm_customer := :NEW.elcm_customer;

		--dbms_output.put_line('l_key~' || l_key);
		--dbms_output.put_line('Calling replicate data...');

		IF NOT elpkss_replication.fn_replicate_data
		(
				l_function_id,
				l_branch_code,
				l_key,
				l_data,
				l_mod_no,
				l_priority,
				l_error_code,
				l_error_prms
		)
		THEN
			debug.pr_debug('LM', 'Returned False from elpkss_replication.fn_replicate_data' || l_error_code);
			dbms_output.put_line('Returned False from elpkss_replication.fn_replicate_data' || l_error_code);



			RAISE err_return;

		END IF;
		-- Kernel 11.3 Chagnes - End

		elpkss_replication.g_stdcif_elcm_customer := NULL;

		--dbms_output.put_line('replicate successful...');
		debug.pr_debug('LM', 'replicate successful...');
		END IF;
	END IF;--Changes done for ELCM INTEGRATION -----------end 2

	debug.pr_debug('LM', 'End of Trigger ELTR_STTM_CUSTOMER');

  EXCEPTION
    WHEN OTHERS THEN
     	debug.pr_debug('LM', 'in whenother of product inside ---->' || sqlerrm);
     	dbms_output.put_line('in whenother of product inside ---->' || sqlerrm);


		RAISE err_return;
END;

/
ALTER TRIGGER "FCC114"."ELTR_STTM_CUSTOMER" DISABLE;

  CREATE OR REPLACE TRIGGER "FCC114"."COTR4_17" AFTER DELETE ON "FCC114"."STTM_CUSTOMER" FOR EACH ROW 
DECLARE
	inilen 			number;
	finlen 			number;
	l_no 				number;
	l_len 			number;
	l_pos				number;
	l_mask  			sttms_bank.cif_mask%type;
	l_auto_gen_cif		sttms_bank.auto_gen_cif%type;


BEGIN


SELECT cif_mask,auto_gen_cif into l_mask,l_auto_gen_cif from sttms_bank
WHERE  auth_stat = 'A' and record_stat = 'O';

if l_auto_gen_cif = 'Y'
then


	inilen := nvl(length(l_mask),0);
	finlen := nvl(length(replace(l_mask,'n','')),0);
	l_len  := inilen-finlen;
	l_pos  := instr(l_mask,'n',1);
	if bofn_is_numeric(:OLD.customer_no) = 1
	then

		l_no   := to_number(substr(:OLD.customer_no,l_pos,l_len));

		INSERT into sttms_customer_srno
		VALUES(:OLD.local_branch,l_no,'A','N');
	end if;

end if;
EXCEPTION
	when dup_val_on_index
	then

		UPDATE sttms_customer_srno
		SET used_flag = 'N'
		WHERE branch_code = :OLD.local_branch
		AND customer_running_no = l_no
		AND used_flag = 'Y';
END;

/
ALTER TRIGGER "FCC114"."COTR4_17" ENABLE;

  CREATE OR REPLACE TRIGGER "FCC114"."COTR3_16" AFTER UPDATE OR INSERT ON "FCC114"."STTM_CUSTOMER" FOR EACH ROW 
  WHEN (NEW.auth_stat = 'A' and (OLD.once_auth = 'N' OR OLD.once_auth is null)) DECLARE
l_auto_gen_cif		sttms_bank.auto_gen_cif%type;
l_mask			sttms_bank.cif_mask%type;
inilen 			number;
finlen 			number;
l_no 				number;
l_len 			number;
l_pos				number;


BEGIN
		select auto_gen_cif,cif_mask into l_auto_gen_cif,l_mask from sttms_bank
		where auth_stat = 'A'
		and record_stat = 'O';
		if l_auto_gen_cif = 'Y'
		then
			inilen := nvl(length(l_mask),0);
			finlen := nvl(length(replace(l_mask,'n','')),0);
			l_len  := inilen-finlen;
			l_pos  := instr(l_mask,'n',1);

			if bofn_is_numeric(:NEW.customer_no) = 1
			then
				l_no   := to_number(substr(:NEW.customer_no,l_pos,l_len));

				delete sttms_customer_srno
				where branch_code = :NEW.local_branch
  				and  CUSTOMER_RUNNING_NO = l_no
  				and actual_dummy = 'A'
  				and used_flag = 'Y';
			end if;
		end if;

END;

/
ALTER TRIGGER "FCC114"."COTR3_16" ENABLE;

  CREATE OR REPLACE TRIGGER "FCC114"."STTR_CUST_UPD" BEFORE UPDATE OF "CAS_CUST" ON "FCC114"."STTM_CUSTOMER" FOR EACH ROW BEGIN
	debug.pr_debug('AC','In trigger sttr_cust_upd');
	UPDATE sttms_cust_account
	SET cas_customer = :new.cas_cust
	WHERE cust_no = :new.customer_no;
	debug.pr_debug('AC','End of trigger sttr_cust_upd');
EXCEPTION
WHEN OTHERS
THEN
	debug.pr_debug('AC','In exception in trigger sttr_cust_upd '||sqlerrm);
END sttr_cust_upd;

/
ALTER TRIGGER "FCC114"."STTR_CUST_UPD" DISABLE;


  GRANT SELECT ON "FCC114"."STTM_CUSTOMER" TO "FCCFEDS";
  GRANT SELECT ON "FCC114"."STTM_CUSTOMER" TO "FCCDEV";
  GRANT SELECT ON "FCC114"."STTM_CUSTOMER" TO "FCCDWH";
  GRANT SELECT ON "FCC114"."STTM_CUSTOMER" TO "FCCECH";
  GRANT SELECT ON "FCC114"."STTM_CUSTOMER" TO "READ_ONLY_ROLE";
  GRANT SELECT ON "FCC114"."STTM_CUSTOMER" TO "AUDITOR";
