CREATE OR REPLACE PROCEDURE PR_DO_MANUAL_PURGE IS
BEGIN
  BEGIN
       EXECUTE IMMEDIATE 'TRUNCATE TABLE FBTB_TXNLOG_MASTER_HIST_BK';
  EXCEPTION
    WHEN OTHERS
    THEN
        NULL;
  END;
  
  BEGIN
    EXECUTE IMMEDIATE 'TRUNCATE TABLE FBTB_TXNLOG_DETAILS_HIST_BK';
  EXCEPTION
    WHEN OTHERS
    THEN
        NULL;
  END;
  
  --PURGE FBTB_TXNLOG_MASTER_HIST
  DBMS_SCHEDULER.CREATE_JOB(JOB_NAME        => 'PURGE_TXNLOG_MASTER_HIST',
                            JOB_TYPE        => 'PLSQL_BLOCK',
                            JOB_ACTION      => 'BEGIN PR_PURGE_TXNLOG_MASTER_HIST; END;',
                            START_DATE      => SYSTIMESTAMP,
                            REPEAT_INTERVAL => NULL,
                            ENABLED         => TRUE,
                            COMMENTS        => 'STREAM FOR PURGE_TXNLOG_MASTER_HIST');
  COMMIT;

  --PURGE FBTB_TXNLOG_DETAILS_HIST
  DBMS_SCHEDULER.CREATE_JOB(JOB_NAME        => 'PURGE_TXNLOG_DETAIL_HIST',
                            JOB_TYPE        => 'PLSQL_BLOCK',
                            JOB_ACTION      => 'BEGIN PR_PURGE_TXNLOG_DETAIL_HIST; END;',
                            START_DATE      => SYSTIMESTAMP,
                            REPEAT_INTERVAL => NULL,
                            ENABLED         => TRUE,
                            COMMENTS        => 'STREAM FOR PURGE_TXNLOG_DETAIL_HIST');
  COMMIT;

  --PURGE MSTB_STP_MSG

  EXECUTE IMMEDIATE 'TRUNCATE TABLE MSTB_STP_MSG';

  --PURGE CSTB_MSG_LOG
  EXECUTE IMMEDIATE 'TRUNCATE TABLE CSTB_MSG_LOG';

  --PURGE SMTB_SMS_ACTION_LOG

  EXECUTE IMMEDIATE 'TRUNCATE TABLE SMTB_SMS_ACTION_LOG';

  --PURGE MSTB_STP_ERR

  EXECUTE IMMEDIATE 'TRUNCATE TABLE MSTB_STP_ERR';

  EXECUTE IMMEDIATE 'TRUNCATE TABLE MSTB_STP_EXCEPTION_MASTER';

  --PURGE GITU_UPLOAD_MASTER

  EXECUTE IMMEDIATE 'TRUNCATE TABLE GITU_UPLOAD_MASTER';

  --PURGE MSTB_EXT_MSG_OUT

  EXECUTE IMMEDIATE 'TRUNCATE TABLE MSTB_EXT_MSG_OUT';
  
  --PURGE GWTB_NOTIFICATIONS_LOG
  EXECUTE IMMEDIATE 'TRUNCATE TABLE GWTB_NOTIFICATIONS_LOG';

  --PURGE STTB_NOTIFICATION

  EXECUTE IMMEDIATE 'TRUNCATE TABLE STTB_NOTIFICATION';
  
  --PURGE STTB_NOTIFICATION_HISTORY

  EXECUTE IMMEDIATE 'TRUNCATE TABLE STTB_NOTIFICATION_HISTORY';

  --PURGE ICTB_DR_INT_ERR

  EXECUTE IMMEDIATE 'TRUNCATE TABLE ICTB_DR_INT_ERR';
  
  --PURGE CSTB_AUDIT_LOG

  EXECUTE IMMEDIATE 'TRUNCATE TABLE CSTB_AUDIT_LOG';
  
END;
/
