SELECT DBMS_METADATA.GET_DDL('PACKAGE_BODY','STPKS_STDCIFI9_CUSTOM','FCC114')
FROM DUAL;

SELECT DBMS_METADATA.GET_DDL('PACKAGE_SPEC','STPKS_STDCIFI9_CUSTOM','FCC114')
FROM DUAL;

SELECT DBMS_METADATA.GET_DDL('PACKAGE_BODY','STPKS_STDCIFI9_MAIN','FCC114')
FROM DUAL;

SELECT DBMS_METADATA.GET_DDL('PACKAGE_SPEC','STPKS_STDCIFI9_MAIN','FCC114')
FROM DUAL;